export const CONSTANTS = {
	FOOTER_HEIGHT: 300,
	BASE_URL: 'http://localhost:8080/api',
	HOME: 'HOME',
	NAVIGATE_TO_PAGE: 'NAVIGATE_TO_PAGE',
	GOT_ALL_CLIENTS: 'GOT_ALL_CLIENTS',
	GOT_USER_LOGIN: 'GOT_USER_LOGIN',
	LOGOUT: 'LOGOUT',
	SELECT_DASHBOARD_INDEX: 'SELECT_DASHBOARD_INDEX',
	GOT_PENDING_CUSTOMER_MANAGER_REQUESTS: 'GOT_PENDING_CUSTOMER_MANAGER_REQUESTS',
	GOT_PENDING_FINANCIAL_MANAGER_REQUESTS: 'GOT_PENDING_FINANCIAL_MANAGER_REQUESTS',
	GOT_PENDING_ADMIN_MANAGER_REQUESTS: 'GOT_PENDING_ADMIN_MANAGER_REQUESTS',
	GOT_PENDING_CMS_REQUESTS: 'GOT_PENDING_CMS_REQUESTS',
	GOT_CLIENT: 'GOT_CLIENT',
	GOT_CLIENT_PROJECT_SUM: 'GOT_CLIENT_PROJECT_SUM'
}